// <auto-generated />
namespace EFProjectSalesApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SalesTargetsPersonAndRegion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SalesTargetsPersonAndRegion));
        
        string IMigrationMetadata.Id
        {
            get { return "201810212327539_SalesTargetsPersonAndRegion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
